sudo: required
language: generic
services:
  - docker

before_install:
  - echo "start image with docker"
  - docker build -t mazino/docker-app -f Dockerfile.dev .
script:
  - docker run -e CI=true mazino/docker-app npm run test -- --coverage

after_success:
  - echo "test end"
